import Head from 'next/head'
import Filter from '@/components/Filter'
import Content from '@/components/Content'
import Header from '@/components/Header'
import { useState } from 'react'

export default function Home() {

  const [selectedStates, setSelectedStates] = useState([])
  const [selectedSchools, setSelectedSchoosl] = useState([])
  const [selectedMajors, setSelectedmajors  ] = useState(5)

  return (
    <>
      <Head>
        <title>BRASA Connect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='bg-primary'>
          <Header/>
          <div className='flex p-[30px]'>
            <Filter
              selectedStates={selectedStates}
            />          
            <Content/>
          </div>
        </div>
      </main>
    </>
  )
}
